name: Fetch Ads-txt
on:
  push:
  schedule:
    - cron: '0 0 1-31/2 * *'
jobs:
  fetch-adstxt:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://kumo.network-n.com/adstxt/?domain=grandislibrary.com
          save-name: ads
          format: txt
      - name: Build and Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master # Pushes the updates to the master branch.
          FOLDER: fetch-api-data-action # The location of the data.json file saved by the Fetch API Data action.
          TARGET_FOLDER: public # Saves the data into the 'data' directory on the master branch.
