name: Fetch Ads-txt
on:
  push:
  schedule:
    - cron: '0 0 1-31/2 * *'
jobs:
  fetch-adstxt:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://kumo.network-n.com/adstxt/?domain=grandislibrary.com
          save-location: public
          save-name: ads
          format: txt
      - name: GitHub Commit & Push
        uses: actions-js/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
