name: Fetch Ads-txt
on:
  push:
  schedule:
    - cron: '0 0 1-31/2 * *'
jobs:
  fetch-adstxt:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://kumo.network-n.com/adstxt/?domain=grandislibrary.com
          save-location: public
          save-name: ads
          format: txt
      - uses: actions/checkout@v2
      - name: Commit adstxt
        run: |
          git config --global user.name 'ikasuu'
          git config --global user.email '[bots]@users.noreply.github.com'
          git commit -am "Updating ads.txt"
          git push
